# See https://www.gitpod.io/docs/config-gitpod-file.

image:
  file: gitpod/Dockerfile

tasks:
  - init: ./sh/configure.sh

vscode:
  extensions:
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-renderers
    - streetsidesoftware.code-spell-checker
    - mutantdino.resourcemonitor
    - innerlee.nvidia-smi
